import * as Lark from '@larksuiteoapi/node-sdk';
import * as fs from 'fs';
import * as path from 'path';

const configPath = path.join(process.env.HOME || '', '.clawdbot', 'clawdbot.json');
const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
const feishuCfg = config.channels?.feishu;
const client = new Lark.Client({ appId: feishuCfg.appId, appSecret: feishuCfg.appSecret, domain: Lark.Domain.Feishu });

const hints: Record<string, string> = {
  "Pets": "家养动物、宠物",
  "Food": "快餐、街边小吃",
  "Flowers": "花园、花卉",
  "Cinema": "电影类型、影院",
  "Burger": "汉堡配料",
  "Book": "书籍部件",
  "Landmass": "大洲、大陆",
  "Drinks": "饮料、饮品",
  "Chess": "国际象棋棋子",
  "Seasons": "四季",
  "Fishing": "钓鱼装备",
  "Islands": "世界岛屿",
  "Dances": "舞蹈风格",
  "Insects": "昆虫",
  "Material": "材料、材质",
  "Airport": "机场区域",
  "Dairy": "乳制品",
  "Fish": "鱼类",
  "Map": "国家",
  "Knight": "中世纪骑士",
  "Gamer": "游戏类型",
  "Device": "家用电器",
  "House": "豪宅、大房子",
  "Jobs": "职业",
  "Footwear": "鞋类",
  "Driving": "驾驶、交通",
  "Explorer": "探险家",
  "Movement": "身体动作",
  "Phase": "物质状态",
  "Cozy": "舒适感受",
  "Zodiac": "黄道星座",
  "Ship": "船只类型",
  "Mailman": "邮政物品",
  "Sculpt": "雕塑类型",
  "Language": "世界语言",
  "Camera": "相机部件",
  "Fog": "雾气、朦胧",
  "Snow": "冰雪形态",
  "Spiky": "带刺的东西",
  "Birds": "鸟类",
  "Minds": "思想家、哲学家",
  "Hockey": "冰球术语",
  "Date": "浪漫约会",
  "Saw": "锯子部件",
  "Actor": "好莱坞男演员",
  "Planet": "太阳系行星",
  "Lessons": "学校科目",
  "Pills": "药物形式",
  "Rainy": "雨天",
  "Breads": "面包种类",
  "Brain": "大脑部位",
  "Elements": "化学元素",
  "Cheese": "奶酪种类",
  "Fitness": "健身活动",
  "Muscles": "肌肉部位",
  "Egypt": "古埃及",
  "Berry": "浆果",
  "Capitals": "世界首都",
  "Makeup": "化妆品",
  "Combat": "格斗武术",
  "Guitar": "吉他配件",
  "Ballet": "芭蕾舞",
  "Unite": "联盟组织",
  "Luxury": "奢侈品",
  "Biomes": "生态群落",
  "Spicy": "辣味食物",
  "Plane": "飞机部件",
  "Rodents": "啮齿动物",
  "Energy": "能量类型",
  "Articles": "文章类型",
  "Disaster": "自然灾害",
  "Primates": "灵长类动物",
  "Coding": "编程语言",
  "Rap": "说唱元素",
  "Water": "著名瀑布",
  "Toys": "儿童玩具",
  "Army": "军衔",
  "Meditate": "冥想修行",
  "Fame": "名声、成名",
  "Linguist": "语言学",
  "Holiday": "公共假日",
  "Gym": "健身器材",
  "William": "莎士比亚戏剧",
  "Canines": "犬科动物",
  "Studies": "名牌大学",
  "Citrus": "柑橘类水果",
  "Aircraft": "飞行器",
  "Grape": "葡萄酒品种",
  "Mushroom": "蘑菇种类",
  "Arctic": "北极动物",
  "Racing": "赛车运动",
  "Help": "帮助、援助",
  "Gemstone": "宝石",
  "Pattern": "星座图案",
  "Fuels": "燃料",
  "Elect": "选举",
  "Crown": "君主头衔",
  "Leader": "美国总统",
  "Hot dog": "热狗配料",
  "Cipher": "密码加密",
  "Symphony": "交响乐",
  "Artworks": "艺术作品形式",
  "Auction": "拍卖会",
  "Beans": "咖啡豆品种",
  "Camping": "露营装备",
  "Play": "乐器演奏",
  "Finance": "金融财务",
  "Medieval": "中世纪",
  "Optics": "光学器具",
  "Navigate": "导航工具",
  "Toddler": "幼儿用品",
  "Families": "动物科属",
  "Stars": "恒星",
  "AI": "人工智能",
  "Division": "行政区划",
  "Speak": "对话交流",
  "Hair": "发质类型",
  "Injuries": "身体损伤",
  "Flu": "感冒症状",
  "Minerals": "矿物",
  "Radiate": "辐射",
  "Hormones": "激素",
  "Eye": "眼睛部位",
  "Shovel": "挖掘动作",
  "Alloy": "合金",
  "Festival": "亚洲节日",
  "Metal": "稀土金属元素",
  "Artifact": "古代文物",
  "Defense": "安保防卫",
  "Particle": "亚原子粒子",
  "New York": "纽约地区",
  "No bones": "无脊椎动物",
  "Legends": "传说故事",
  "Hello": "问候语",
  "PhD": "学术研究",
  "OK sign": "同意表达",
  "Justice": "司法",
  "Prisoner": "囚犯",
  "Space": "太空现象",
  "Western": "西部牛仔",
  "Lock": "安全可靠",
  "Legs": "腿部部位",
  "Pyramids": "埃及神话",
  "Shaft": "矿井采矿",
  "Farming": "农场种植",
  "Sliding": "滑行运动",
  "Painting": "绘画颜料",
  "Rice": "米饭菜品",
  "Heart": "爱情浪漫",
  "Hippie": "嬉皮士文化",
  "Robot": "机器人",
  "Greece": "希腊字母",
  "Dynamics": "物理运动学",
  "Lakes": "大湖",
  "Nuclear": "原子核",
  "Italy": "意大利城市",
  "Pointing": "指示代词",
  "Skin": "肤质类型",
  "Build": "公共建筑",
  "Policies": "政治体制",
  "Strength": "力量",
  "Message": "通讯方式",
  "Views": "哲学思想",
  "Organs": "人体器官",
  "Tarot": "塔罗牌",
  "Voices": "声部类型",
  "Poetry": "诗歌体裁",
  "Meals": "一日三餐",
  "Alchemy": "炼金术",
  "Paganism": "异教崇拜",
  "Present": "当前、现在",
  "Secret": "秘密、隐秘",
  "Equidae": "马科动物",
  "Leather": "皮革材质",
  "Castle": "城堡结构",
  "Display": "显示屏技术",
  "Cultures": "古代文明",
  "Warriors": "日本武士",
  "Lie": "欺骗",
  "Violin": "管弦乐器",
  "Anagram": "字母重组",
  "Drum": "手鼓种类",
  "Wreath": "胜利荣耀",
  "Zen": "禅宗修行",
  "Network": "网络设备",
  "Customs": "海关贸易",
  "Mortgage": "房贷术语",
  "Concrete": "混凝土施工",
  "Memes": "网络恶搞",
  "Alkanes": "烷烃",
  "Evaluate": "评估分析",
  "Quest": "探索追寻",
  "Beards": "胡须造型",
  "Yinyang": "阴阳平衡",
  "Foodie": "美食爱好者",
  "Opera": "歌剧",
  "Harbor": "港口码头",
  "Street": "街道场景",
  "Chimera": "奇美拉神兽",
  "Carriage": "马车",
  "Gaits": "马的步态",
  "Earth": "地球结构",
  "Violins": "小提琴",
  "Grammar": "语法词性",
  "Coastal": "海岸景观",
  "Wheel": "车轮部件",
  "Industry": "工业生产",
  "Prefix": "数量前缀",
  "Breeds": "猫品种",
  "Landmark": "世界地标",
  "Rivers": "著名河流",
  "Coast": "海岸",
  "Skincare": "护肤品",
  "Dynasty": "皇室家族",
  "Priest": "神职人员",
  "Maps": "地图元素",
  "Screen": "电子屏幕",
  "Alarm": "闹钟警报",
  "Singing": "歌唱元素",
  "Genetics": "遗传学",
  "Sports": "体育运动",
  "Furniture": "家具",
  "Deck": "扑克牌",
  "Toolbox": "工具箱",
  "Garments": "衣物服装",
  "Veggie": "蔬菜",
  "Fruits": "水果",
  "Chair": "座椅类型",
  "Hats": "帽子",
  "Cleaning": "清洁用品",
  "Shoes": "鞋子款式",
  "Bird": "鸟类",
  "Seafood": "海鲜",
  "Dogs": "狗品种",
  "Eats": "快餐小吃",
  "Folklore": "民间传说",
  "Drupes": "核果",
  "Picnic": "野餐",
  "Pastry": "糕点甜点",
  "Wind": "管乐器",
  "Mall": "商场",
  "Strings": "弦乐器",
  "Jewelry": "珠宝首饰",
  "Reptiles": "爬行动物",
  "Pirate": "海盗",
  "Beach": "海滩",
  "Sea fish": "海鱼",
  "Birthday": "生日派对",
  "Charger": "充电设备",
  "Transport": "交通工具",
  "Whiskers": "有胡须的动物",
  "Shapes": "几何形状",
  "Babies": "婴儿用品",
  "Sailor": "水手航海",
  "Candy": "糖果",
  "Keys": "钥匙用途",
  "Lawn": "草坪花园",
  "3D": "立体图形",
  "Vampire": "吸血鬼",
  "Desert": "沙漠",
  "Purple": "紫色物品",
  "Yellow": "黄色物品",
  "Rain": "下雨天",
  "Pairs": "成对物品",
  "Xmas": "圣诞节",
  "Mail": "邮件邮寄",
  "Chef": "厨师",
  "Tools": "职业工具",
  "Supplies": "办公用品",
  "Utensils": "餐具",
  "Arts": "艺术形式",
  "Survival": "生存装备",
  "Baking": "烘焙原料",
  "Medical": "医疗用品",
  "Eco-items": "环保物品",
  "Decor": "家居装饰",
  "Aquatics": "水上运动",
  "Icons": "图标符号",
  "Halloween": "万圣节"
};

async function resolveWikiToken(wikiToken: string): Promise<string> {
  const res = await (client as any).request({
    method: 'GET',
    url: `/open-apis/wiki/v2/spaces/get_node`,
    params: { token: wikiToken },
  });
  return res.data.node.obj_token;
}

async function readSheet(token: string, sheetId: string, range: string): Promise<any[][]> {
  const res = await fetch(`http://127.0.0.1:18796/read?token=${token}&sheetId=${sheetId}&range=${range}`);
  const data = await res.json() as any;
  return data.values || [];
}

async function writeValues(spreadsheetToken: string, sheetId: string, range: string, values: any[][]): Promise<void> {
  const fullRange = `${sheetId}!${range}`;
  const res = await (client as any).request({
    method: 'PUT',
    url: `/open-apis/sheets/v2/spreadsheets/${spreadsheetToken}/values`,
    data: { valueRange: { range: fullRange, values } },
  });
  if (res.code !== 0) throw new Error(`Failed: ${res.msg}`);
  console.log(`Wrote ${values.length} rows to ${fullRange}`);
}

async function main() {
  const wikiToken = 'CTpNwhHIpik1jUk0DhjcOpbNntc';
  const sheetId = 'a0a147';
  
  console.log('Resolving wiki token...');
  const spreadsheetToken = await resolveWikiToken(wikiToken);
  console.log(`Spreadsheet token: ${spreadsheetToken}`);
  
  // 读取 B 列（类别名）
  console.log('Reading categories...');
  const rows = await readSheet(spreadsheetToken, sheetId, 'B1:B310');
  
  // 生成 S 列数据
  const sValues: string[][] = rows.map((row, i) => {
    if (i === 0) return ['类别提示词(中文)'];
    const cat = row[0];
    return [hints[cat] || ''];
  });
  
  // 分批写入（每批50行）
  const batchSize = 50;
  for (let i = 0; i < sValues.length; i += batchSize) {
    const batch = sValues.slice(i, i + batchSize);
    const startRow = i + 1;
    const endRow = startRow + batch.length - 1;
    console.log(`Writing rows ${startRow}-${endRow}...`);
    await writeValues(spreadsheetToken, sheetId, `S${startRow}:S${endRow}`, batch);
  }
  
  console.log('Done!');
}

main().catch(console.error);
